name: Rails CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0' # Specify your Ruby version here

    - name: Install dependencies
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3

    - name: Set execute permissions on Rails scripts
      run: chmod +x bin/rails bin/rake

    - name: Set up database
      run: |
        bin/rails db:setup
        bin/rails db:migrate

    - name: Run tests
      run: bin/rails test

    # Optional: Add additional steps for linting, code analysis, etc.
